### ISSUE TITLE
rivet installation failure

### ISSUE THREAD

**Issue by sihyunjeon** [mg5amcnlo/HEPToolsInstallers#3]
https://bugs.launchpad.net/mg5amcnlo/+bug/2054883

While investigating the bug I realized that RIVET was not being properly installed in my docker image and I got the error message below

```
pluginBES/BESIII_2019_I1756876.cc: In member function ‘virtual void Rivet::BESIII_2019_I1756876::finalize()’:
pluginBES/BESIII_2019_I1756876.cc:168:54: error: ‘error’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  168 |             mult   ->addPoint(x, sigma, ex, make_pair(error,error));
      |                                             ~~~~~~~~~^~~~~~~~~~~~~
cc1plus: some warnings being treated as errors
make[2]: *** [Makefile.tmp.TJ7kz8UPzb:17: tmp.zNX1yoGs.o] Error 1
make[2]: Leaving directory '/tmp/tmplox_wacq/Rivet-3.1.8/analyses'
make[1]: *** [Makefile:540: RivetBESAnalyses.so] Error 3
make[1]: Leaving directory '/tmp/tmplox_wacq/Rivet-3.1.8/analyses'
make: *** [Makefile:564: install-recursive] Error 1
 Finished RIVET installation
```

So the bug actually seems to coming from rivet input BESIII_2019_I1756876

https://gitlab.com/hepcedar/rivet/-/blob/rivet-3.1.8/analyses/pluginBES/BESIII_2019_I1756876.cc?ref_type=tags
https://gitlab.com/hepcedar/rivet/-/blob/release-4-0-x/analyses/pluginBES/BESIII_2019_I1756876.cc?ref_type=heads

I am not sure if this is the right way to do it but I am testing the following
giving `CXXFLAGS=-Wno-error` before `./configure` in local heptoolsinstallers
Will report back what happens

**Comment by sihyunjeon** [comment]
In the installation log I see that the -Wno-error is properly tossed to installation
```
-Werror=uninitialized -Werror=delete-non-virtual-dtor -fopenmp -Wno-error
```
But there are some default flags `-Werror` coming from rivet installer itself.

And after this RIVET runs fine.

What concerns me is the following
- Why did RIVET authors failed to identify this issue (=why was this not issue for them)? Is there something wrongly/differently happening for RIVET installer in MadGraph and thus we are only seeing this when trying to install RIVET through MadGraph?
- Assuming that @oliviermattelaer you agree patching with `-Wno-error` like above is OK, should we just ignore the other `-Werror` arguments?

**Comment by sihyunjeon** [comment]
I am going to test rivet3.1.9 installation using HEPToolsInstaller
- To see if the same error occurs or not
- Just to update to newer version

**Comment by oliviermattelaer** [comment]
No objection to add the -Wno-error if this helps

**Comment by sihyunjeon** [comment]
v3.1.9 seems to not work without -Wno-error option.
I'll test the option on v3.1.9 and make a PR accordingly if things are all good

**Comment by sihyunjeon** [comment]
https://github.com/mg5amcnlo/HEPToolsInstallers/pull/4

**Comment by sihyunjeon** [comment]
https://gitlab.com/hepcedar/rivet/-/merge_requests/827
